# Generated by Django 5.1.1 on 2024-10-20 19:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='room_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='reservation', to='hotel.room', verbose_name='Room Number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
