# Generated by Django 5.1.1 on 2024-10-20 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_reservation_room_id_alter_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservation', to='hotel.customer', verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_type_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='reservation', to='hotel.paymenttype', verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservation', to='hotel.staff', verbose_name='Staff Name'),
        ),
    ]
