# Generated by Django 5.1.1 on 2024-10-21 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_reservation_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='booking', to='hotel.customer', verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='booking', to='hotel.paymenttype', verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='booking', to='hotel.room', verbose_name='Room Number'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='booking', to='hotel.staff', verbose_name='Staff Name'),
        ),
    ]
