# Generated by Django 5.1.1 on 2024-10-21 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_booking_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='booking', to='hotel.paymenttype', verbose_name='Mode of Payment'),
        ),
    ]
