# Generated by Django 5.1.1 on 2024-10-21 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_booking_payment_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payment', to='hotel.customer', verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='hotel.paymenttype', verbose_name='Payment Type'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='staff_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payment', to='hotel.staff', verbose_name='Staff Name'),
        ),
    ]
