# Generated by Django 5.1.1 on 2024-10-21 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_alter_payment_payment_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='booking', to='hotel.payment', verbose_name='Payment Details'),
        ),
    ]
