# Generated by Django 5.1.1 on 2024-10-21 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_booking_payment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_type_id',
        ),
    ]
