# Generated by Django 5.1.1 on 2024-10-21 01:25

import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_remove_booking_payment_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_number',
            field=models.CharField(default=hotel.models.generate_payment_number, max_length=11, unique=True),
        ),
    ]
