# Generated by Django 5.1.1 on 2024-10-21 01:34

import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_payment_receipt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='receipt_number',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(default=hotel.models.generate_payment_number, max_length=11, unique=True, verbose_name='Payment Number'),
        ),
    ]
