# Generated by Django 5.1.1 on 2024-10-21 01:39

import django.db.models.deletion
import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_remove_payment_receipt_number_payment_payment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='booking', to='hotel.payment', verbose_name='Payment Number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(default=hotel.models.generate_payment_number, editable=False, max_length=11, unique=True, verbose_name='Payment Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='otp_code',
            field=models.CharField(default=hotel.models.generate_otp, editable=False, max_length=6, unique=True, verbose_name='OTP Code'),
        ),
    ]
