# Generated by Django 5.1.1 on 2024-10-21 06:03

import django.db.models.deletion
import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_alter_booking_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default=hotel.models.generate_booking_number, editable=False, max_length=11, unique=True, verbose_name='Booking Number'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='hotel.paymenttype', verbose_name='Payment Mode'),
        ),
    ]
