# Generated by Django 5.1.1 on 2024-10-21 06:03

import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_booking_booking_number_alter_payment_payment_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(default=hotel.models.generate_booking_number, editable=False, max_length=15, unique=True, verbose_name='Booking Number'),
        ),
    ]
