# Generated by Django 5.1.1 on 2024-10-21 06:30

import hotel.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_alter_booking_booking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_number',
            field=models.CharField(default=hotel.models.generate_payment_number, editable=False, max_length=15, unique=True, verbose_name='Payment Number'),
        ),
    ]
