# Generated by Django 5.1.1 on 2024-10-21 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_alter_customer_id_alter_customer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.roomstatus'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.roomtype'),
        ),
    ]
