# Generated by Django 5.1.1 on 2024-10-21 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_alter_room_room_status_id_alter_room_room_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment_type_id',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=3, null=True, verbose_name='Room Number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.roomstatus', verbose_name='Room Status'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.roomtype', verbose_name='Room Type'),
        ),
    ]
