# Generated by Django 5.1.1 on 2024-10-21 07:25

import hotel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_remove_reservation_payment_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_number',
            field=models.CharField(default=hotel.models.generate_reservation_number, editable=False, max_length=15, unique=True, verbose_name='Booking Number'),
        ),
    ]
