# Generated by Django 5.1.1 on 2024-10-21 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_alter_reservation_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('Checked-in', 'Checked-in'), ('Checked-out', 'Checked-out'), ('None', 'None')], default='None', max_length=11),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='payment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservation', to='hotel.payment', verbose_name='Payment Number'),
        ),
    ]
