# Generated by Django 5.1.1 on 2024-10-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='description',
        ),
        migrations.AddField(
            model_name='roomtype',
            name='description',
            field=models.CharField(default=1, max_length=200, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
