# Generated by Django 5.1.1 on 2024-10-22 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_alter_roomtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('Receptionist', 'Receptionist'), ('Admin', 'Admin'), ('SuperAdmin', 'SuperAdmin')], default='Receptionist', max_length=13),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotel.user', verbose_name='Username'),
        ),
    ]
