name: Django Test 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-12  # macOS Monterey

    steps:
      - name: Run tests
        run: |
          python manage.py test





